[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"

[dependencies.futures-util]
version = "0.3.31"
default-features = false
features = ["alloc", "async-await", "async-await-macro"]
