[package]
name = "user_space"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.10"
common = { version = "0.1.0", path = "../common" }
embedded-graphics = "0.8.1"
heapless = "0.8.0"
tinytga = "0.5.0"
x86_64 = "0.15.2"

[[bin]]
name = "user_space"
test = false
bench = false
