# Timeout in seconds that Limine will use before automatically booting.
timeout: 0
serial: yes
verbose: yes

# The entry name that will be displayed in the boot menu.
/Code Runner
    protocol: limine
    kernel_path: boot():/boot/kernel
